### ISSUE TITLE
Package build fails with Visual Studio 2015

### ISSUE THREAD

**Issue by sunsided** [eliaskousk/conan-gflags#1]
For some reason, the `2.1.2` source zip you're downloading does not contain a fix crucial to building on Windows with Visual Studio 2015, which is [this line](https://github.com/gflags/gflags/blob/74bcd20c0e5b904a67e37abf0c1262824ff9030c/src/windows_port.h#L66), resulting in

```
...\.conan\data\gflags\2.1.2\dwerner\testing\build\63da998e3642b50bee33f4449826b2d623661505\gflags-2.1.2\src\windows_port.cc(62): 
error C2084: function 'int snprintf(char *const ,const std::size_t,const char *const ,...)' already has a body
```

Would it be an option to pull the sources via git submodule instead and release a, well, not-quite-2.1.2 version?

**Comment by eliaskousk** [comment]
I added a new testing branch and associated package. It clones the upstream git repo instead of using a release archive. Keep in mind that is tracks the master branch which currently builds fine with GCC 5.4. Please notify me if it breaks in the future and I will make the package checkout a specific commit sha id.

You can find it here:
[gflags/2.1.2@eliaskousk/testing](https://www.conan.io/source/gflags/2.1.2/eliaskousk/testing)
